### ISSUE TITLE
Add tool tip to YouTube URL form element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/YouTubeImport#11]
Add “tool tip” to YouTube URL. 
When user hovers over the tool tip icon (eg. “i” in a circle), display a pop-up message: “Copy the URL from your browser’s URL bar or the YouTube “share” link”

(See YouTube Usability Report Item 2.1.1.3; incl. sample figure)

**Comment by NedHenry** [comment]
fixed in eb71c5becc34dcefa3d594b28d49609c036dcebb
