### ISSUE TITLE
Add tool tip to "User Role/Responsibility" form element

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/YouTubeImport#14]
Add tool tip (see fig. 1 above for format) to “Responsibility” (formerly “User Role”) field.
When user hovers over the tool tip icon, display a pop-up message: “This will determine the Dublin Core field in which the YouTube user/channel name will appear.”

(YouTube Usability Report Item 2.1.1.6)

**Comment by NedHenry** [comment]
fixed in eb71c5becc34dcefa3d594b28d49609c036dcebb
