### ISSUE TITLE
Change current post-submission header message from “Your video was imported…” to “Go to Items or Collections to view imported video”

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/YouTubeImport#19]
Users who are unsure where to find their imported video were more likely to re-scan the page (at which point they did see this header message).

(This is dependent on Issue #18 )

YouTube Usability Report item 2.2.1.3

**Comment by NedHenry** [comment]
Fixed in 5138c622ce52b55d570965dfdca89b861fb3ba6c
