### ISSUE TITLE
Display the video player (instead of the thumbnail) in an Omeka Exhibit page

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/YouTubeImport#22]
When the user selects a YouTube video item to add to their exhibit, the embedded video player is placed in the exhibit page. A viewer can click the play button and play the embedded video directly from an exhibit page.

YouTube Usability Report 2.4.1.1; includes sample figure

**Comment by NedHenry** [comment]
Fixed in 0e9b4e01dc9b356422981c463235ddc778c8ca12

**Comment by JessWaggs** [comment]
Neither video or thumbnail display on the Exhibit page (example: http://exhibit-dev.library.ucsc.edu/exhibits/show/all-item-types/ucsf-mini-medical-school-serie).

**Comment by JessWaggs** [comment]
Works in a different page! (Not sure what went wrong on that other page...)
