### ISSUE TITLE
Missing semicolon at the end of code on line 74 of YouTubeImportPlugin.php

### ISSUE THREAD

**Issue by ianchan** [UCSCLibrary/YouTubeImport#36]
Hi,
There's a missing semicolon at the end of code on line 74 of YouTubeImportPlugin.php.
https://github.com/UCSCLibrary/YouTubeImport/blob/c708f969d063dd343e23080b84566435271b9ccb/YouTubeImportPlugin.php#L74

Best regards,
Ian Chan

**Comment by rschwab** [comment]
Thank you for the report and the fix!
