### ISSUE TITLE
Fatal Error while importing a video

### ISSUE THREAD

**Issue by gustavokira** [UCSCLibrary/YouTubeImport#5]
Hi, I'm getting an error at line 184 on 'plugins/YouTubeImport/helpers/import.php' file. It seems that some  problem when trying to call _addPlayerElement() function from a static context...  

I manage to import a video changing the function to static and making a static call at line 184 and taking out the dollar sign from the plugins/YouTubeImport/helpers/import.php file, at line 52. It looks like the typo  error that was mentioned at #4.

It worked, but I really did`t read your code, so I can`t say if does not cause some troubles in other places.

After the video was added, the application throws a lot of warnings and notices, but it seems that all from other plugins. Since I`m not a omeka expert, I really don`t know why or if its something with your plug-in or its someone elses fault.

If helps, i can make a pull request to facilitate the code review!

tks!

**Comment by NedHenry** [comment]
Many thanks for this report and for your contribution! I will look over it
tomorrow in detail.
Best,
Ned
