### ISSUE TITLE
Error when trying to view public page

### ISSUE THREAD

**Issue by ayeliab** [UCSCLibrary/YouTubeImport#7]
Hi, thanks for this plugin! I'm running into the following issue when I try to use it however:

The video seems to import fine from Youtube as an item in Omeka and seems fine from the back end. However, if I try to view the public page, I get the following error:

Omeka has encountered an error

Exception
String could not be parsed as XML

#0 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/plugins/SocialBookmarking/helpers/SocialBookmarkingFunctions.php(49): SimpleXMLElement->__construct('')
#1 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/plugins/SocialBookmarking/helpers/SocialBookmarkingFunctions.php(59): social_bookmarking_get_services_xml()
#2 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/plugins/SocialBookmarking/helpers/SocialBookmarkingFunctions.php(89): social_bookmarking_get_services()
#3 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/plugins/SocialBookmarking/SocialBookmarkingPlugin.php(128): social_bookmarking_toolbar('http://library....', 'Edmund Hillary ...', '')
#4 [internal function]: SocialBookmarkingPlugin->hookPublicItemsShow(Array)
#5 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Omeka/Plugin/Broker.php(157): call_user_func(Array, Array)
#6 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/globals.php(188): Omeka_Plugin_Broker->callHook('public_items_sh...', Array)
#7 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/themes/seasons/items/show.php(19): fire_plugin_hook('public_items_sh...', Array)
#8 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Omeka/View.php(117): include('/mnt/stor16-wc2...')
#9 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/mnt/stor16-wc2...')
#10 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('items/show.php')
#11 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('items/show.php', NULL)
#12 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#13 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#14 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#16 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#17 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()
#18 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#19 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#20 /mnt/stor16-wc2-dfw1/575637/library.americanalpineclub.org/web/content/index.php(23): Omeka_Application->run()
#21 {main}

Please help. Thank you!

**Comment by NedHenry** [comment]
Hi there,
It looks like this error is being thrown by the Social Bookmarking plugin
as it tries to read in its settings from an XML file. Do you see this error
only on Youtube imported items, or on all the public page for all items? My
first advice would be to update the Social Bookmarking plugin and see if
the problem goes away. Please post again if the problem seems Youtube
specific and/or doesn't go away when the other plugin is updated.

Hope this helps!

Ned Henry
UCSC Library

**Comment by ayeliab** [comment]
Yes, we updated our social bookmarking plugin and the problem is resolved. Many thanks!
